# Generated by Django 3.1 on 2020-08-12 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20200811_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='compra_id',
            new_name='compra',
        ),
    ]
