# Generated by Django 3.1 on 2020-08-12 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20200811_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compra',
        ),
        migrations.AddField(
            model_name='product',
            name='client_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='market.client'),
            preserve_default=False,
        ),
    ]
