# Generated by Django 3.1 on 2020-08-12 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_compra_compra_id_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='compra_id_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product'),
        ),
    ]
