# Generated by Django 3.1 on 2020-08-12 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20200811_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='compra_id_id',
            new_name='compra_id',
        ),
    ]
