# Generated by Django 3.1 on 2020-08-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_auto_20200812_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compra_id',
        ),
        migrations.AddField(
            model_name='compra',
            name='compra_id',
            field=models.ManyToManyField(to='market.Product'),
        ),
    ]
