# Generated by Django 3.1 on 2020-08-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_auto_20200812_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compra_id',
        ),
    ]
