# Generated by Django 3.1 on 2020-08-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_auto_20200812_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='client_id',
        ),
    ]
