# Generated by Django 3.1 on 2020-08-12 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_remove_compra_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='client_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='market.client'),
            preserve_default=False,
        ),
    ]
