# Generated by Django 3.1 on 2020-08-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_compra_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='product_id',
        ),
        migrations.AddField(
            model_name='compra',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='market.product'),
            preserve_default=False,
        ),
    ]
