# Generated by Django 3.1 on 2020-08-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_auto_20200812_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='product_id',
        ),
        migrations.AddField(
            model_name='compra',
            name='product_id',
            field=models.ManyToManyField(to='market.Product'),
        ),
    ]
