# Generated by Django 3.1 on 2020-08-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_auto_20200812_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=10),
        ),
    ]
