# Generated by Django 3.1 on 2020-08-12 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_auto_20200812_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.client'),
        ),
        migrations.RemoveField(
            model_name='compra',
            name='product_id',
        ),
        migrations.AddField(
            model_name='compra',
            name='product_id',
            field=models.ManyToManyField(to='market.Product'),
        ),
    ]
