# Generated by Django 3.1 on 2020-08-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0032_auto_20200817_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
